site_name = "Documentação Go"
site_url = "https://github.com/impacta-gb/projeto-ctt-ap2-klg3.git"
site_description = "Documentação completa da linguagem Go"
site_author = "Grupo CTT-AP2"

[theme]
name = "material"
language = "pt"
features = [
    "navigation.expand",   
    "search.highlight"
]

[[theme.palette]]
scheme = "slate"
primary = "blue"
accent = "light blue"
toggle = { icon = "material/weather-sunny", name = "Modo claro" }

[[theme.palette]]
scheme = "default"
primary = "blue"
accent = "light blue"
toggle = { icon = "material/weather-night", name = "Modo escuro" }

markdown_extensions = [
    { pymdownx.highlight = { anchor_linenums = true } },
    "pymdownx.superfences",
    "admonition",
    "pymdownx.details",
    "tables",
    "attr_list",
    "md_in_html"
]
nav = [
    { "Início" = "index.md" },
    { "Fundamentos" = [
        { "Introdução e Instalação" = "01-introducao_instalacao.md" },
        { "Sintaxe Básica e Variáveis" = "02-sintaxe.md" },
        { "Estruturas de Controle" = "03-estruturas.md" }
    ]},
    { "Estruturas de Dados" = [
        { "Arrays, Slices e Maps" = "04-arrays_slices_maps.md" },
        { "Structs e Métodos" = "05-structs-metodos.md" }
    ]},
    { "Tratamento de Erros" = "06-tratamento-erros.md" },
    { "Concorrência" = [
        { "Concorrência I: Goroutines" = "07-concorrencia-1.md" },
        { "Concorrência II: Channels" = "08-concorrencia-2.md" }
    ]},
    { "Gerenciamento de Pacotes (Go Modules)" = "09-gerenciamento-pacotes.md" },
    { "Testes Automatizados em Go" = "91-testes-automatizados.md" }
]
